"""Add notification acknowledgement fields

Revision ID: 0e069566736d
Revises: 20260621_0003
Create Date: 2026-06-23 17:27:35.154958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e069566736d'
down_revision = '20260621_0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_acknowledged', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('notifications', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('acknowledged_at')
        batch_op.drop_column('is_acknowledged')
    # ### end Alembic commands ###
